version: '3'
services:
  nginx:
    image: nginx:1.13.5
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./data/html:/var/www/html:ro
      - ./cert:/etc/nginx/cert:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
